sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

install:
  - stack setup
  - (cd test/resources/test-01 ; stack setup)
  - export PATH=~/.stack/programs/x86_64-linux/ghcjs-0.2.0.20151001_ghc-7.10.2/bin:$PATH
  - which ghcjs

script:
  - stack test --ghc-options=-Werror
  - export CASHER_TIME_OUT=500

cache:
  directories:
    - $HOME/.stack
    - $HOME/.ghcjs
