name: wai-shake
version: "0.1"
category: Web
author: Linh Nguyen, Sönke Hahn
maintainer: linh.nguyen@zalora.com, soenkehahn@gmail.com
synopsis: serve compilation results through a wai application
description: serve compilation results through a wai application
license: "BSD3"

ghc-options:
  "-Wall -fno-warn-name-shadowing"

dependencies:
  - base == 4.*
  - string-conversions
  - language-ecmascript
  - bytestring
  - wai
  - process
  - data-default
  - http-types
  - filepath
  - temporary
  - directory == 1.2.*
  - interpolate
  - shake
  - wai-app-static >= 3.1.2
  - case-insensitive
  - text
  - template-haskell
  - th-lift
  - cryptohash
  - base64-bytestring

library:
  source-dirs:
    - src

executables:
  serve-ghcjs:
    main: serve-ghcjs.hs
    source-dirs:
      - drivers
      - src
    dependencies:
      - warp
      - getopt-generics == 0.12.*

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - mockery
      - hspec-wai
      - silently
      - QuickCheck
      - wai-extra
      - zlib
